import { OrderStatusData } from "./types";

// Default data for demonstration
export const defaultOrderData: OrderStatusData = {
  orderNumber: "ORD-20260115-000008",
  orderDate: "January 15, 2026",
  orderStatus: "processing",
  estimatedDelivery: "Jan 20-22, 2026",
  paymentMethod: "Cash on Delivery (COD)",
  paymentStatus: "pending",
  paymentStatusMessage: "Payment will be collected upon delivery. Please keep the exact amount ready.",
  items: [
    {
      id: "1",
      name: "Premium Wireless Headphones",
      image: "",
      price: 299.0,
      quantity: 2,
      color: "Matte Black",
      sku: "WH-2024-BLK",
      description: "High-quality wireless headphones with active noise cancellation and premium sound quality",
    },
    {
      id: "2",
      name: "Smart Fitness Watch Pro",
      image: "",
      price: 449.0,
      quantity: 1,
      color: "Space Gray",
      sku: "FW-2024-GRY",
      description: "Advanced fitness tracking with heart rate monitor, GPS, and water resistance up to 50m",
    },
    {
      id: "3",
      name: "Portable Bluetooth Speaker",
      image: "",
      price: 129.0,
      quantity: 3,
      color: "Ocean Blue",
      sku: "BS-2024-BLU",
      description: "Waterproof portable speaker with 360° sound and 24-hour battery life",
    },
    {
      id: "4",
      name: "Fast Wireless Charging Pad",
      image: "",
      price: 79.0,
      quantity: 2,
      color: "Carbon Black",
      sku: "WC-2024-BLK",
      description: "15W fast wireless charging with anti-slip surface and LED indicator",
    },
  ],
  subtotal: 5213.0,
  shipping: 149.0,
  tax: 260.65,
  discount: 100.65,
  total: 5522.0,
  shippingAddress: {
    name: "John Anderson",
    addressLine1: "4521 Maple Street, Apartment 3B",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11201",
    country: "United States",
    phone: "+1 (555) 123-4567",
    email: "john.anderson@email.com",
  },
  billingAddress: {
    name: "John Anderson",
    addressLine1: "4521 Maple Street, Apartment 3B",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11201",
    country: "United States",
    phone: "+1 (555) 123-4567",
    email: "john.anderson@email.com",
  },
  trackingTimeline: [
    {
      status: "Order Confirmed",
      date: "Jan 15, 2026 - 3:45 PM",
      description: "Your order has been confirmed and is being prepared for shipment.",
      completed: true,
      icon: "check",
    },
    {
      status: "Processing",
      date: "Expected: Jan 16, 2026",
      description: "Your items are being picked and packed at our warehouse.",
      completed: true,
      icon: "box",
    },
    {
      status: "Shipped",
      date: "Expected: Jan 17, 2026",
      description: "Your order will be handed over to our shipping partner.",
      completed: false,
      icon: "truck",
    },
    {
      status: "In Transit",
      date: "Expected: Jan 18-20, 2026",
      description: "Your package is on its way to the destination.",
      completed: false,
      icon: "plane",
    },
    {
      status: "Out for Delivery",
      date: "Expected: Jan 20, 2026",
      description: "Your package is out for delivery in your area.",
      completed: false,
      icon: "building",
    },
    {
      status: "Delivered",
      date: "Expected: Jan 20-22, 2026",
      description: "Your order has been delivered successfully.",
      completed: false,
      icon: "house",
    },
  ],
  confirmationEmail: "john.anderson@email.com",
};
